name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - run: npm ci

      - name: Run ESLint
        run: npm run lint

      - name: Run Test
        run: npm run test

      - name: Run Build
        run: npm run build
